stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - docker
    - test
  script:
    - echo "Сборка приложения..."
    - echo "Build completed"

test-job:
  stage: test
  tags:
    - docker
    - test
  script:
    - echo "Тестирование..."
    - echo "Tests passed"
